name: Generate Snake

on:
  # Corre automaticamente a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  # Permite correr manualmente quando quiseres
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          # Nome do teu utilizador GitHub
          github_user_name: gbrito11
          # Onde guarda o gif e o svg (aqui definimos a cor para dark mode)
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
